trigger:
  - "*"

variables:
  buildConfiguration: "Release"
  packageName: "$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip"

stages:
  - stage: "Build"
    displayName: "Build the web application"
    jobs:
      - job: "Build"
        displayName: "Build job"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - script: echo $(packageName)
          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "**/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration $(buildConfiguration)"
              projects: "**/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Publish the project - $(buildConfiguration)"
            inputs:
              command: "publish"
              projects: "**/CCN.Api.csproj"
              publishWebProjects: false
              arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
              zipAfterPublish: true

          - publish: "$(Build.ArtifactStagingDirectory)"
            artifact: drop

  - stage: "Staging"
    displayName: "Deploy to the staging environment"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: "Deply Staging"
        pool:
          vmImage: "ubuntu-latest"
        environment: staging
        variables:
          - group: staging
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - task: AzureWebApp@1
                  displayName: "Deploy Staging"
                  inputs:
                    azureSubscription: 'staging-br-bpo-ccn'
                    appType: 'webAppLinux'
                    appName: 'staging-api-bpo-ccn'
                    package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
                    runtimeStack: 'DOTNETCORE|3.1'
                    deploymentMethod: auto
                    
  - stage: "Production"
    displayName: "Deploy to the production environment"
    dependsOn: Staging
    jobs:
      - deployment: Deploy
        displayName: "Deply Production"
        pool:
          vmImage: "ubuntu-latest"
        environment: production
        variables:
          - group: "production"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - task: AzureWebApp@1
                  displayName: "Deploy Production"
                  inputs:
                    azureSubscription: 'br-bpo-ccn'
                    appType: 'webAppLinux'
                    appName: 'api-bpo-ccn'
                    package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
                    runtimeStack: 'DOTNETCORE|3.1'
                    deploymentMethod: auto
